name: Java CI Appartment Store

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name : Checkout main branch from VSC 
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Check target folder
      run : |
        cd target
        ls -a
        
    - name: Running tests
      run: mvn --batch-mode --update-snapshots verify -f pom.xml
